# This is a basic workflow to help you get started with Actions

name: Build 

# Controls when the workflow will run
on: [push, workflow_dispatch]
env:
  URL: localhost
  HUGO_VERSION: 0.154.5
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_website:
    # The type of runner that the job will run on
    name: Build The Website Using Hugo 
    runs-on: ubuntu-latest

    steps:
      - name: Check Hugo Cache
        id: hugo-cache
        uses: actions/cache@v5
        with:
          key: hugo-${{env.HUGO_VERSION}}
          path: hugo_${{env.HUGO_VERSION}}_linux-amd64.deb

      
      - name: Get Hugo
        if: ${{steps.hugo.outputs.cache-hit != 'true'}}
        run: |
          echo $HUGO_VERSION
          wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_linux-amd64.deb
          
      - name: Install Hugo
        run: |
          sudo apt update
          sudo dpkg -i hugo_$HUGO_VERSION_linux-amd64.deb
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: Build Hugo Website
        run: |
          hugo build -b $URL -d build

      - name: Package Website
        run: tar -cf build.tar build

      - name: Upload the Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: latest-build
          path: build.tar
          overwrite: true

      
